<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="280" started-at="2019-01-15T01:53:07Z" finished-at="2019-01-15T01:53:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="280" started-at="2019-01-15T01:53:07Z" finished-at="2019-01-15T01:53:08Z">
      <class name="testCases.UnitTestStringVerify">
        <test-method status="PASS" signature="testCaseForLongestWord()[pri:0, instance:testCases.UnitTestStringVerify@27a5f880]" name="testCaseForLongestWord" duration-ms="42" started-at="2019-01-15T01:53:08Z" finished-at="2019-01-15T01:53:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseForLongestWord -->
        <test-method status="FAIL" signature="testCaseforStringLenght()[pri:0, instance:testCases.UnitTestStringVerify@27a5f880]" name="testCaseforStringLenght" duration-ms="6" started-at="2019-01-15T01:53:08Z" finished-at="2019-01-15T01:53:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [21] but found [28]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [21] but found [28]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at testCases.UnitTestStringVerify.testCaseforStringLenght(UnitTestStringVerify.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseforStringLenght -->
      </class> <!-- testCases.UnitTestStringVerify -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
